name: CI
permissions:
  contents: read

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
      - name: Setup and Install
        uses: ./.github/actions/setup-and-install

      - name: Lint
        run: pnpm lint

      - name: Format Check
        run: pnpm format

      - name: Security Audit
        run: pnpm audit --prod

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test
